version: "3"

services:

  willamette-api:
    build:
      context: "."
      args:
        develop: "true"
    ports:
      - 5000:5000
    depends_on:
      - quaerere-arangodb
    env_file:
      - ".env.willamette-api"
    environment:
      WILLAMETTE_APP: api

  quaerere-arangodb:
    image: "quaerereplatform/quaerere-arangodb:latest"
    ports:
      - 8529:8529
    env_file:
      - ".env.arangodb"
    volumes:
      - "../../volumes/arangodb:/var/lib/arangodb3"
      - "../../volumes/arangodb-apps:/var/lib/arangodb3-apps"
