version: '3'

services:
  test_db:
    image: "quaerereplatform/quaerere-arangodb:latest"
    environment:
      ARANGO_ROOT_PASSWORD: password

  web_app:
    build:
      context: ..
    depends_on:
      - test_db
    environment:
      WILLAMETTE_APP: api
      ARANGODB_USER: quaerere
      ARANGODB_PASSWORD: password
      ARANGODB_ROOT_PASSWORD: password
      ARANGODB_HOST: http://test_db:8529
      FLASK_SECRET_KEY: integration-testing
      FLASK_ENV: development
      FLASK_APP: willamette.app:create_app
      GUNICORN_HOST: 0.0.0.0
      GUNICORN_LOGLEVEL: debug

  test_runner:
    build: .
    depends_on:
      - web_app
      - test_db
    environment:
      ARANGODB_ROOT_PASSWORD: password
      ARANGODB_USER: quaerere
      ARANGODB_PASSWORD: password
      APP_API_URL: http://web_app:5000/api/
